### ISSUE TITLE
A line of documentation would help :-)

### ISSUE THREAD

**Issue by Guillawme** [wackywendell/coomasie-imgfix#1]
Hi there, 

Would you mind explaining in one sentence what this script does? Perhaps also put this explanation in a readme file? Github is a great resource but it would be even greater and more useful for non-programmers (like me) if useful things were documented.
I have the slight feeling that this script could be of use to me (as a PhD student in biochemistry, I routinely take pictures of coomassie-stained gels). But I am not able to read the code in details to understand what it exactly does to the gel images it reads in the input directory.

Thanks in advance. :smiley:

**Comment by wackywendell** [comment]
Yes, I'll work on it! I wrote this in an afternoon one day for my wife; its a basic bash script for automatically increasing the legibility of coomassie gels. But a full README would make more sense!

**Comment by wackywendell** [comment]
Closed with 74dfc7f9da.

**Comment by Guillawme** [comment]
Thanks a lot. :+1:
